### ISSUE TITLE
Now OAuth2 authorization

### ISSUE THREAD

**Issue by fmarzocca** [dehsgr/node-red-contrib-netatmo-cameracontrol#1]
Are you aware that starting from october 2022 the "gran type password" will not work anymore? Is this pacage ready for the new authorization OAuth2 process?

**Comment by dehsgr** [comment]
I'm aware of it. According docs this should not be an issue as you/we are authenticating against (y)our own development account. OAUTH isn't an requirement there. Nevertheless I'll monitor this situation...

**Comment by fmarzocca** [comment]
Sorry but I am afraid you are wrong. I talked to Netatmo and they said that the grant password authorization will be completely removed in October. So this node will stop working.

**Comment by dehsgr** [comment]
I don't agree with you! As per https://dev.netatmo.com/apidocumentation/oauth#authorization-code is clearly documented:

_For personal use **only** (the account with which the API application have been created), you can also authenticate with the ["](https://dev.netatmo.com/apidocumentation/oauth#client_credential)[**Client credentials" grant type**](https://dev.netatmo.com/apidocumentation/oauth#client-credential) in which the username and the password should be sent along with the request._

**Comment by fmarzocca** [comment]
The documentation is not updated. Inform yourself!
Have you received this email?

"_To improve the security of our products, we inform you that the Client Credentials grant type method will be completely removed. It will no longer be possible to authenticate with the username and password of the user.
The effective date of this update is October 2022_."

I am not in charge of convincing you. If you insist with this dumb reaction, the node will dead on 30 sept 2022.
Anyway, I have just removed it from my NR.

**Comment by dehsgr** [comment]
...I'm a little taken aback by your choice of words. You should not forget that this is a recreational project that will not cost you anything in the end.

Feel free to contribute with an appropriate source code customization to keep the node alive if you feel that Netatmo's documentation has not been updated. In any case, simply making demands is not a good style...

Of course I received the email. The link I used is also from that very email. To that extent, I have to assume for now that Netatmo is referencing updated information in its information.

**Comment by fmarzocca** [comment]
I have only asked if you are planning to update the node or not. That's it. 

As it doesn't seem so, I removed the node and I am migrating elsewhere,.

**Comment by fmarzocca** [comment]
This is the answer I got from a Netatmo developer:

_Hello!
Thank you for your message. 
I confirm that the username and password section will not be allowed anymore, it will return an "invalid access token" error. 
If you already have a token you do not need to proceed with modifications and you can simply refresh the token. However, for new user access you will need to proceed as described on this page: https://dev.netatmo.com/apidocumentation/oauth._
